config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  devise_for :recipes
  resources :users
  resources :recipes

  post '/recipes/create', to: 'recipes#create', as: 'recipes_create'

  get '/recipes/new', to: 'recipes#new', as: 'recipes_new'
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :user
	validates :name, presence: true, uniqueness: true

	def self.search(search)
  		if search
    		find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  		else
    		find(:all)
 		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :recipes
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def index
  		@recipes = Recipe.all
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def new
    	@recipe = Recipe.new
    end
    
	def create
		@recipe = Recipe.new({:name => (params[:recipe])[:name], :level => (params[:recipe])[:level], 
			:description => (params[:recipe])[:description], :instructions => (params[:recipe])[:instructions], :user_id => current_user})
		@recipe.user = current_user
		if @recipe.save
			flash[:notice] = "You successfully created your own recipe!"
			redirect_to user_path(current_user)	
		else
			redirect_to recipes_new_path
			flash[:error] = @recipe.errors.full_messages.to_sentence
		end
	end

	def update
		@recipe = Recipe.find(params[:id])
		if @recipe.update_attributes(params[:trip])
			flash[:notice] = "Successfully updated your recipe!"
			redirect_to user_path(current_user)
		end
	end

end

app/controllers/recipesfeed_controller.rb
class RecipesfeedController < ApplicationController

	def index
  		@projects = Project.search(params[:search])
	end

	def show
		@recipe = Recipe.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/recipesfeed_helper.rb
module RecipesfeedHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <%= link_to 'RecipesFeed', recipes_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Collooking" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Collooking" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/recipes/index.html.erb
<h3>Recipes</h3>
  <% @recipes.each do |recipe| %>
    <%= link_to recipe.name, recipe_path(recipe), :method => "get" %>
    </p>
  <% end %>
        

app/views/recipes/new.html.erb
<h1>Create a New Recipe!</h1>

<%= simple_form_for Recipe.new, url: {action: "create"}, :html => { :multipart => true } do |f| %>
    <%= f.input :name, label: 'Name:'%>
    <%= f.label :ingredient, 'Ingredients:'%><br />
    <%= f.text_area :description, :rows => 10%><br />
    <%= f.label :description, 'Description:'%><br />
    <%= f.text_area :description, :rows => 10%>
    <%= f.input :instructions, label: 'Instructions:'%>
    <%= f.input :level, label: 'Level:', hint:'Mark the level you think this recipe deserves'%>
    <%= f.button :submit%>
<%end%>


app/views/recipes/show.html.erb
<h3><%= @recipe.name %></h3>
<img src="assets/omelette.jpg">
<p>Level: <%=@recipe.level%></p>
<p>Description: <%=@recipe.description%></p>
<p>Ingredients: <%= simple_format(@recipe.ingredients) %></p>
<p>Instructions: <%= simple_format(@recipe.instructions) %></p>

app/views/recipesfeed/show.html.erb
<div id="content_box">
	<div id="content">
		<h3><%= @recipe.name %></h3>
		<img src="assets/omelette.jpg">
		<p>Level: <%=@recipe.level%></p>
		<div id="des_ingre">
			<p>Description: <%=@recipe.description%></p>
			<p>Ingredients: <%= simple_format(@recipe.ingredients) %></p>
		</div>
		<p>Instructions: <%= simple_format(@recipe.instructions) %></p>
	</div>
</div>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>Welcome <%= @user.name if @user.name %>!</h3>
<h3>Let's get cooking!</h3>

<% form_tag recipes_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<%= button_to "Create a Recipe!", recipes_new_path, :class => "button medium", :method => :get %>

<h3>My Recipes:</h3>
<%recipe = Recipe.where(user_id: @user.id)%>
<%recipe.each do |recipe|%>
	<%name = recipe.name%>	
	<%= link_to name, recipe_path(recipe), :method => "get" %>
	</p>
	<p>Level: <%=recipe.level%></p>
	<p>Description: <%=recipe.description%></p>

	<%= button_to "Edit a Recipe!", recipes_new_path, :class => "button medium", :method => :get %>

<%end%>

app/views/visitors/index.html.erb
<link rel="stylesheet" type="text/css" href="assets/stylesheets/style.css" />

<body>
<div id="content_box">
	<div id="content">
		<h1 id="title"><center>Welcome to Collooking</center></h1>
		<!-- <p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p> -->
		<h3>Top Recipes</h3>

		<!-- <img src="assets/salmon.jpg" class="locationicon">\
		<img src="assets/chicken_asparagus.jpg" class="locationicon">
		<img src="assets/hamburger.jpg" class="locationicon">
		<img src="assets/mashed_potatoes.jpg" class="locationicon"> -->

		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
		  <!-- Indicators -->
		  <ol class="carousel-indicators">
		    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
		    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
		    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
		  </ol>
		 
		  <!-- Wrapper for slides -->
		  <div class="carousel-inner">
		    <div class="item active">
		      <img src="assets/salmon.jpg" alt="..." height="1500" width="800">
		      <div class="carousel-caption">
		          <h3>Pan Seared Salmon with a zest of Lemon and Bell Peppers</h3>
		      </div>
		    </div>
		    <div class="item">
		      <img src="assets/chicken_asparagus.jpg" alt="..." height="1500" width="700">
		      <div class="carousel-caption">
		          <h3>Seasoned Chicken topped with herbs and a side of asparagus</h3>
		      </div>
		    </div>
		    <div class="item">
		      <img src="assets/hamburger.jpg" alt="..." height="1500" width="800">
		      <div class="carousel-caption">
		          <h3>Juicy 100% Beef Patty Burger</h3>
		      </div>
		    </div>
		  </div>
		 
		  <!-- Controls -->
		  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
		    <span class="glyphicon glyphicon-chevron-left"></span>
		  </a>
		  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
		    <span class="glyphicon glyphicon-chevron-right"></span>
		  </a>
		</div> <!-- Carousel -->
		<h3>Top Chefs</h3>


		<img src="assets/joeson_chiang.jpg" class="chefs">
		<p class="chefs">Joeson Chiang<p>
		<img src="assets/aaron_lopez.jpg" class="chefs">
		<p class="chefs">Aaron Lopez<p>
		<img src="assets/steven_cheng.jpg" class="chefs">
		<p class="chefs">Steven Cheng<p>

		</br></br>
		<h3 id="all_recipes_title">All Recipes</h3>
		</br>
		<div id="all_recipes">
			<%recipe = Recipe.all%>
			<%recipe.each do |recipe|%>
			<%name = recipe.name%>	
			<%= link_to name, recipe_path(recipe), :method => "get" %>
			</p>
			<p>Level: <%=recipe.level%></p>
			<%end%>
		</div>

		</br></br>
		<p>Search For Your Recipes</p>
		<!-- The terms of service are available at http://www.google.com/cse/docs/tos.html -->
		<form name="cse" id="searchbox_demo" action="http://www.google.com/cse">
		  <input type="hidden" name="cref" value="" />
		  <input type="hidden" name="ie" value="utf-8" />
		  <input type="hidden" name="hl" value="" />
		  <input name="q" type="text" size="40" />
		  <input type="submit" name="sa" value="Search" />
		</form>
		<!--<script type="text/javascript" src="https://www.google.com/cse/tools/onthefly?form=searchbox_demo&lang="></script>-->

		<!--<div id='cse' style='width:100%'>Loading</div>
		<script src="http://www.google.com/jsapi" type="text/javascript"></script>
		<script type="text/javascript">google.load('search', '1');
          google.setOnLoadCallback(function(){var cse = new google.search.
          CustomSearchControl();cse.draw('cse');}, true);</script>-->
	</div>
</div>
</body>
